name: Run SonarQube with Maven
on: push
jobs:
  sonarscan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build along with Maven cloud
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=sonar-demo-org-may-sonal_sonar-demo-project-may -Dsonar.organization=sonar-demo-org-may-sonal -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=7edf3ce6bf08f0b22c0f16e8ef264ca029060f47
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: 7edf3ce6bf08f0b22c0f16e8ef264ca029060f47
